### ISSUE TITLE
Crash in NotificationHandlerActivity.onCreate

### ISSUE THREAD

**Issue by grote** [grote/BlitzMail#11]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.grobox.blitzmail.lite/de.grobox.blitzmail.NotificationHandlerActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2092)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
at android.app.ActivityThread.access$600(ActivityThread.java:148)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1219)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4812)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
at org.json.JSONTokener.nextValue(JSONTokener.java:94)
at org.json.JSONObject.<init>(JSONObject.java:154)
at org.json.JSONObject.<init>(JSONObject.java:171)
at de.grobox.blitzmail.NotificationHandlerActivity.onCreate(NotificationHandlerActivity.java:43)
at android.app.Activity.performCreate(Activity.java:5080)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
... 11 more
```

**Comment by ByteHamster** [comment]
Is this the same crash?

```
D/StatusBar( 8478): Clicked on content of 0|de.grobox.blitzmail|0|null|10058
I/ActivityManager( 8334): START u0 {flg=0x10000000 cmp=de.grobox.blitzmail/.NotificationHandlerActivity} from uid 10058 on display 0
V/WindowManager( 8334): addAppToken: AppWindowToken{32dab06 token=Token{14d0a1e1 ActivityRecord{20fa0f48 u0 de.grobox.blitzmail/.NotificationHandlerActivity t7064}}} to stack=1 task=7064 at 0
I/ActivityManager( 8334): Start proc 13543:de.grobox.blitzmail/u0a58 for activity de.grobox.blitzmail/.NotificationHandlerActivity
W/InputMethodManagerService( 8334): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@1131d5c7 attribute=null, token = android.os.BinderProxy@2f4e4d96
D/AndroidRuntime(13543): Shutting down VM
W/InputMethodManagerService( 8334): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2044d7f4 attribute=null, token = android.os.BinderProxy@2f4e4d96
E/AndroidRuntime(13543): FATAL EXCEPTION: main
E/AndroidRuntime(13543): Process: de.grobox.blitzmail, PID: 13543
E/AndroidRuntime(13543): java.lang.RuntimeException: Unable to start activity ComponentInfo{de.grobox.blitzmail/de.grobox.blitzmail.NotificationHandlerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
E/AndroidRuntime(13543): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2356)
E/AndroidRuntime(13543): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
E/AndroidRuntime(13543): at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime(13543): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime(13543): at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(13543): at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(13543): at android.app.ActivityThread.main(ActivityThread.java:5293)
E/AndroidRuntime(13543): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13543): at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(13543): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(13543): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(13543): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
E/AndroidRuntime(13543): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
E/AndroidRuntime(13543): at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
E/AndroidRuntime(13543): at org.json.JSONTokener.nextValue(JSONTokener.java:94)
E/AndroidRuntime(13543): at org.json.JSONObject.<init>(JSONObject.java:156)
E/AndroidRuntime(13543): at org.json.JSONObject.<init>(JSONObject.java:173)
E/AndroidRuntime(13543): at de.grobox.blitzmail.NotificationHandlerActivity.onCreate(NotificationHandlerActivity.java:42)
E/AndroidRuntime(13543): at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime(13543): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(13543): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2309)
E/AndroidRuntime(13543): ... 11 more
```

**Comment by grote** [comment]
Yes, or at least very similar.
