### ISSUE TITLE
NullPointerException in AsyncMailTask

### ISSUE THREAD

**Issue by grote** [grote/BlitzMail#12]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at de.grobox.blitzmail.AsyncMailTask.onPostExecute(AsyncMailTask.java:110)
	at de.grobox.blitzmail.AsyncMailTask.onPostExecute(AsyncMailTask.java:31)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5293)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

```

**Comment by grote** [comment]
fixed in 532c58ea5b840
