### ISSUE TITLE
spurious but frequent failures with smtp.openmailbox.org

### ISSUE THREAD

**Issue by rgh36167** [grote/BlitzMail#21]
after configuring smtp.openmailbox.org (which has some hurdles - like login name must be name@openmailbox.org and sender name must match it exactly, no  shortcuts, aliases etc) it mostly works. 

However - in 1 of perhaps 5 cases I get this error:

"Authentification failed. Please check your username and password!"

"try again" usually works.

The errors are just too frequent to think it is a random failure, already had over 20 in 3 days. Never had this type of failure while using google smtp when used in similar conditions.

The network connection is sometimes extremely slow - but that should not cause above error message?

Tested on a Moto G with freshly updated system.

**Comment by grote** [comment]
Sorry, I don't have a openmailbox.org account to test with. You could check your logcat output for more information and if there's nothing ask their support to tell you what they see from their side for the time you try to connect.

**Comment by rgh36167** [comment]
Found only this, a few seconds tried again and it worked.

```
V/WindowManager( 2236): addAppToken: AppWindowToken{1b56cd3c token=Token{c78b32f ActivityRecord{23897d0e u0 de.grobox.blitzmail/.SendActivity t3011}}} to stack=1 task=3011 at 0

I/SendActivity(24255): Using TLS Encryption...

D/ha
D/AsyncMailTask(24255): ERROR: null
W/System.err(24255): javax.mail.AuthenticationFailedException
W/System.err(24255):    at javax.mail.Service.connect(Service.java:319)
W/System.err(24255):    at javax.mail.Service.connect(Service.java:169)
W/System.err(24255):    at javax.mail.Service.connect(Service.java:118)
W/System.err(24255):    at javax.mail.Transport.send0(Transport.java:188)
W/System.err(24255):    at javax.mail.Transport.send(Transport.java:118)
W/System.err(24255):    at de.grobox.blitzmail.MailSender.sendMail(MailSender.java:66)
W/System.err(24255):    at de.grobox.blitzmail.AsyncMailTask.doInBackground(AsyncMailTask.java:65)
W/System.err(24255):    at de.grobox.blitzmail.AsyncMailTask.doInBackground(AsyncMailTask.java:34)
W/System.err(24255):    at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/System.err(24255):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(24255):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err(24255):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(24255):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(24255):    at java.lang.Thread.run(Thread.java:818)
```

**Comment by grote** [comment]
Does this mean that you got it working eventually?

**Comment by rgh36167** [comment]
it works - but out of 10 times 2-3 times it fails with "Authentification failed"  which is the mysterious part. After retrying  it usually works again, sometimes I have to retry several times.

**Comment by grote** [comment]
It is really mysterious. I can only suggest to get in touch with your provider to get to the bottom of this.
